apiVersion: v1
kind: Pod
metadata:
  name: multicontainer

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.25"
          memory: "128Mi"
